name: mrt-scraper

windows:
  - logs:
      name: dev
      panes:
        - mv log log-old && echo "" > log && tail -f log
  - santolan-anapolis:
      name: dev
      panes:
        - ruby mrt-scraper.rb -s santolan-anapolis
  - shaw-boulevard:
      name: server
      panes: 
        - ruby mrt-scraper.rb -s shaw-boulevard
